package froq

// ClinicalTrials.gov: active clinical trials for neural crest genes.
// Source: ClinicalTrials.gov API v2
// Generated by normalizers/from_clinicaltrials.py -- 95 genes

genes: {
	"ADAM10": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT02891213"
				title:  "Study of the Role of Soluble Forms of RAGE (sRAGE/esRAGE) as Diagnostic and Prognostic Biomarkers of Systemic Lupus Erythematosus."
				status: "UNKNOWN"
			},
		]
	}
	"ALDH1A2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"AXIN2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"BMP2": {
		_in_clinicaltrials: true
		active_trial_count: 22
		clinicaltrials_studies: [
			{
				nct_id: "NCT03745300"
				title:  "Comparative Evaluation Of 1.2% Atorvastatin and 1.2% Simvastatin Gel Local Drug Delivery And Redelivery In Chronic Periodontitis Subjects With Diabetes Mellitus: A Randomized Controlled Clinical Trial."
				status: "COMPLETED"
				phase:  "Phase 2/Phase 3"
			},
			{
				nct_id: "NCT05369091"
				title:  "Salivary Bmp-2 Levels & Radiographic Measurement Of Bone Density at Extracted Tooth"
				status: "COMPLETED"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT06522438"
				title:  "Hyaluronic Acid and Octenidine Gel as an Adjunct to Non-surgical Periodontal Treatment"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT04149080"
				title:  "Effects of Simvastatin Gel on Bone Neoformation in Post-extraction Sockets: a Randomized Controlled Trial"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT01308996"
				title:  "Clinical Study of INFUSE® Bone Graft Compared to Autogenous Bone Graft for Vertical Ridge Augmentation"
				status: "WITHDRAWN"
			},
		]
	}
	"BMP4": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"BMP7": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT03202355"
				title:  "The Effect of OrthoPulse Photobiomodulation on the Rate of Tooth Movement During Alignment With Fixed Appliances"
				status: "TERMINATED"
			},
		]
	}
	"CDH11": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"CDH2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"CDH6": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"CHD7": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"CTNNB1": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT04812119"
				title:  "Genotype-phenotype Correlations in Children and Adults With CTNNB1 Mutation"
				status: "COMPLETED"
			},
		]
	}
	"CXCR4": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"DCT": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT05643573"
				title:  "A Study to Learn How Well the Study Treatment Asundexian Works and How Safe it is Compared to Apixaban to Prevent Stroke or Systemic Embolism in People With Irregular and Often Rapid Heartbeat (Atrial Fibrillation), and at Risk for Stroke"
				status: "TERMINATED"
				phase:  "Phase 3"
			},
			{
				nct_id: "NCT05552326"
				title:  "A Study of Olezarsen Administered Subcutaneously to Participants With Severe Hypertriglyceridemia"
				status: "COMPLETED"
				phase:  "Phase 3"
			},
		]
	}
	"DLL1": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT06636435"
				title:  "A Phase I, First in Human Study of CBA-1205, Anti-DLK1 Monoclonal Antibody in Patients With Advanced Solid Tumors, Hepatocellular Carcinoma (HCC), Melanoma, and Pediatric Cancer"
				status: "RECRUITING"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT07162038"
				title:  "Phase I Trial Integrating HLA-Haploidentical Anti-CD19 CAR-T Cells With Post-Transplantation Cyclophosphamide-Based HLA-Haploidentical Hematopoietic Cell Transplantation"
				status: "RECRUITING"
				phase:  "Phase 1"
			},
		]
	}
	"DLX2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"DLX3": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT01746121"
				title:  "Amelogenesis Imperfecta"
				status: "TERMINATED"
			},
		]
	}
	"DLX5": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"DLX6": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"ECE1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"EDN1": {
		_in_clinicaltrials: true
		active_trial_count: 5
		clinicaltrials_studies: [
			{
				nct_id: "NCT05691426"
				title:  "Assessment of the Effect of Non-surgical Periodontal Treatment on Endothelial Function- a Prospective Study"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT01418014"
				title:  "Adolescent Master Protocol"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT06784869"
				title:  "The Efficacy of Scaling and Root Planing on Endothelin-1 Level"
				status: "NOT_YET_RECRUITING"
			},
			{
				nct_id: "NCT07326033"
				title:  "Efficacy and Safety of Allogenic Cultured Adipose-derived Mesenchymal Stromal Cell Injections on MoUth Fibrosis and Handicap in Patients With Systemic sclEroderma"
				status: "NOT_YET_RECRUITING"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT03510390"
				title:  "Metformin in Head and Neck Squamous Cell Carcinoma: Effect on Tissue Oxygenation"
				status: "COMPLETED"
			},
		]
	}
	"EDN3": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"EDNRA": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"EDNRB": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"ERBB3": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"ETS1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"EVC": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT01267981"
				title:  "Efficacy of Small Bowel Preparation in Capsule Endoscopy"
				status: "COMPLETED"
				phase:  "Phase 3"
			},
		]
	}
	"FGF8": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"FGFR1": {
		_in_clinicaltrials: true
		active_trial_count: 8
		clinicaltrials_studies: [
			{
				nct_id: "NCT07292168"
				title:  "A Phase 1b/2 Study of the Safety and Efficacy of the Monoclonal Antibody OM-RCA-01 in Patients With Metastatic Tumors Expressing Fibroblast Growth Factor Receptor 1"
				status: "RECRUITING"
				phase:  "Phase 1/Phase 2"
			},
			{
				nct_id: "NCT06160752"
				title:  "Safety and Anti-Tumor Activity of TYRA-200 in Advanced Cholangiocarcinoma With Activating FGFR2 Gene Alterations"
				status: "RECRUITING"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT03822117"
				title:  "Efficacy and Safety of Pemigatinib in Previously Treated Locally Advanced/Metastatic or Surgically Unresectable Solid Tumor Malignancies Harboring Activating FGFR Mutations or Translocations (FIGHT-207)"
				status: "TERMINATED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT04125693"
				title:  "Roll-over Study to Continue Treatment With the Investigational Drug Rogaratinib and to Further Test Its Safety"
				status: "COMPLETED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT01928459"
				title:  "Phase 1b Trial of BGJ398/BYL719 in Solid Tumors"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
		]
	}
	"FGFR2": {
		_in_clinicaltrials: true
		active_trial_count: 8
		clinicaltrials_studies: [
			{
				nct_id: "NCT04238715"
				title:  "A Study of E7090 in Participants With Unresectable Advanced or Metastatic Cholangiocarcinoma With Fibroblast Growth Factor Receptor (FGFR) 2 Gene Fusion"
				status: "ACTIVE_NOT_RECRUITING"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT06160752"
				title:  "Safety and Anti-Tumor Activity of TYRA-200 in Advanced Cholangiocarcinoma With Activating FGFR2 Gene Alterations"
				status: "RECRUITING"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT03822117"
				title:  "Efficacy and Safety of Pemigatinib in Previously Treated Locally Advanced/Metastatic or Surgically Unresectable Solid Tumor Malignancies Harboring Activating FGFR Mutations or Translocations (FIGHT-207)"
				status: "TERMINATED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT04604132"
				title:  "Derazantinib Alone or in Combination With Paclitaxel, Ramucirumab or Atezolizumab in Gastric Adenocarcinoma"
				status: "TERMINATED"
				phase:  "Phase 1/Phase 2"
			},
			{
				nct_id: "NCT04972253"
				title:  "Phase I BLASST-3 Trial"
				status: "WITHDRAWN"
				phase:  "Phase 1"
			},
		]
	}
	"FGFR3": {
		_in_clinicaltrials: true
		active_trial_count: 7
		clinicaltrials_studies: [
			{
				nct_id: "NCT04003610"
				title:  "Pemigatinib + Pembrolizumab vs Pemigatinib Alone vs Standard of Care for Urothelial Carcinoma (FIGHT-205)"
				status: "TERMINATED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT00106977"
				title:  "Clinical Study of Muenke Syndrome (FGFR3-Related Craniosynostosis)"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT07218380"
				title:  "A Study of Vepugratinib (LY3866288) in Participants With Cancer in the Urinary Tract"
				status: "RECRUITING"
				phase:  "Phase 3"
			},
			{
				nct_id: "NCT04972253"
				title:  "Phase I BLASST-3 Trial"
				status: "WITHDRAWN"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT02872714"
				title:  "A Study to Evaluate the Efficacy and Safety of Pemigatinib (INCB054828) in Subjects With Urothelial Carcinoma - (FIGHT-201)"
				status: "COMPLETED"
				phase:  "Phase 2"
			},
		]
	}
	"FN1": {
		_in_clinicaltrials: true
		active_trial_count: 6
		clinicaltrials_studies: [
			{
				nct_id: "NCT05474820"
				title:  "Saliva Irisin Level is Higher and Related With Interleukin 6 in Generalized Periodontitis"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05573321"
				title:  "The Effect of Blood Flow Restriction (Bfr) Exercise on Acute Systemic Myokine Levels in Healthy Trained Men"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT01066533"
				title:  "Immunohistochemical Study of Human Teeth Pulp Capped With Mineral Trioxide Aggregate (MTA) and Novel Endodontic Cement (NEC)"
				status: "TERMINATED"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT06847984"
				title:  "Antimicrobial Effect of Curcumin Versus Chlorohexidine on Oral Microbiome"
				status: "NOT_YET_RECRUITING"
			},
			{
				nct_id: "NCT05505084"
				title:  "Alveolar Ridge Preservation Following Tooth Extraction."
				status: "ACTIVE_NOT_RECRUITING"
			},
		]
	}
	"FOXD3": {
		_in_clinicaltrials: true
		active_trial_count: 8
		clinicaltrials_studies: [
			{
				nct_id: "NCT06880094"
				title:  "Study of Congenital Orofacial Clefts by Implementing Optical Genome Mapping"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT02818231"
				title:  "Mechanisms of Cancerogenesis of Woodworkers Adenocarcinomas"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT01924364"
				title:  "Effect of Concentrating Endogenous Stromal Cells in the Fat Graft Using TGI Device"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05949112"
				title:  "Toothbrush in the Genesis and Prevention of Dental Recessions"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT01573026"
				title:  "Five Year Survival Study Evaluating the Genesis Dental Implant System"
				status: "UNKNOWN"
			},
		]
	}
	"GATA4": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"GBX2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"GDNF": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT06327503"
				title:  "Salivary Signal Molecules for Neural and Vascular Homeostasis in T2DM"
				status: "COMPLETED"
			},
		]
	}
	"GFRA1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"HAND1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"HAND2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"IRF6": {
		_in_clinicaltrials: true
		active_trial_count: 25
		clinicaltrials_studies: [
			{
				nct_id: "NCT06776471"
				title:  "Clinical Evaluation of Two Different Pit and Fissure Sealants"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT03034837"
				title:  "Effectiveness and Economic Evaluation of Glass Ionomer Material Using as Dental Sealant"
				status: "COMPLETED"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT02668874"
				title:  "A Clinical Trial Comparing Isolite® vs. Cotton Roll Isolation in the Placement of Dental Sealants"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT07330089"
				title:  "Retention of Pits and Fissure Sealants on Non Carious vs Initial Carious Enamel Lesions in Posterior Teeth"
				status: "NOT_YET_RECRUITING"
			},
			{
				nct_id: "NCT02649816"
				title:  "Effectiveness of Resin Sealants: Retrospective Cohort Study"
				status: "COMPLETED"
			},
		]
	}
	"ITGB1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"JAG1": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT02963077"
				title:  "A Safety and Pharmakokinetic Study of A4250 Alone or in Combination With A3384"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT06506734"
				title:  "Dental Dyschromia and Quality of Life in Early Prolonged Hyperbilirubinemia"
				status: "NOT_YET_RECRUITING"
			},
		]
	}
	"KIT": {
		_in_clinicaltrials: true
		active_trial_count: 275
		clinicaltrials_studies: [
			{
				nct_id: "NCT01954212"
				title:  "Stroke Oral healthCare pLan Evaluation"
				status: "COMPLETED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT06764043"
				title:  "Molar-Incisor Hypomineralization Vs Periodontal Health"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT02359318"
				title:  "Enamel Damages Following De-bracketing From Infiltrated Surfaces"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05083572"
				title:  "Effect of Probiotic on Gut Microbiome and Bacterial Translocation in Healthy Asian Volunteers"
				status: "UNKNOWN"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT05196061"
				title:  "Human Skin and Gut Mycobiome and Bacteriome Comprehensive Registry"
				status: "RECRUITING"
			},
		]
	}
	"LEF1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"MEF2C": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"MITF": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"MMP2": {
		_in_clinicaltrials: true
		active_trial_count: 11
		clinicaltrials_studies: [
			{
				nct_id: "NCT06017817"
				title:  "Antibacterial Photodynamic Therapy in the Management of Peri-implantitis"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT04335526"
				title:  "A Clinical Study to Assess the Effect of Change of Bile Acid on the PD and Safety of Metformin and Microbiome Profiles"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT06540690"
				title:  "Comparison of Palatal Wound Healing in Diabetic and Non-diabetic Patients"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT05171400"
				title:  "A New Drug Delivery System - Silk Fibroin Film Loaded or Not With Insulin on Palatal Mucosa Wound Healing"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT05675241"
				title:  "Characterizing the Inflammation Around Dental Implants"
				status: "UNKNOWN"
			},
		]
	}
	"MMP9": {
		_in_clinicaltrials: true
		active_trial_count: 38
		clinicaltrials_studies: [
			{
				nct_id: "NCT06522438"
				title:  "Hyaluronic Acid and Octenidine Gel as an Adjunct to Non-surgical Periodontal Treatment"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT02891213"
				title:  "Study of the Role of Soluble Forms of RAGE (sRAGE/esRAGE) as Diagnostic and Prognostic Biomarkers of Systemic Lupus Erythematosus."
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT04730687"
				title:  "Er,Cr:YSGG and Diode Lasers in the Treatment of Peri-implantitis"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT07008599"
				title:  "Assessment of Inflammatory Biomarkers in Molar-Incisor Hypomineralization-Affected First Permanent Molars"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT06545812"
				title:  "Immune Response During the Conservative and Minimal Invasive Treatment of Pain Caused by Lumbar Disc Herniation"
				status: "RECRUITING"
			},
		]
	}
	"MSX1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"MSX2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"MYCN": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT01121419"
				title:  "The Role of IMP3 Expression in Patients With Neuroblastoma"
				status: "COMPLETED"
			},
		]
	}
	"NF1": {
		_in_clinicaltrials: true
		active_trial_count: 10
		clinicaltrials_studies: [
			{
				nct_id: "NCT04888936"
				title:  "Clinical, Genetic, and Epidemiologic Study of Children and Adults With RASopathies"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT06120036"
				title:  "Dosing and Tolerability of Deoxycholic Acid vs. Polidocanol in the Treatment of Neurofibromatosis Type 1 Cutaneous Neurofibromas"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT04463316"
				title:  "GROWing Up With Rare GENEtic Syndromes"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT05361811"
				title:  "Acceptance and Commitment Therapy for Caregivers of Children With a RASopathy: An Internal Pilot Feasibility Study and Follow-up Randomized Controlled Trial"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT03504501"
				title:  "Synaptic Plasticity and Cognitive Function in RASopathies"
				status: "TERMINATED"
				phase:  "Phase 2"
			},
		]
	}
	"NGFR": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"NKX2-5": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"NOTCH1": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT01476592"
				title:  "A Biological Study of Resveratrol's Effects on Notch-1 Signaling in Subjects With Low Grade Gastrointestinal Tumors"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT01158274"
				title:  "RO4929097 and Capecitabine in Treating Patients With Refractory Solid Tumors"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
		]
	}
	"NOTCH2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"NR2F1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"NR2F2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"NRP1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"PAX3": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"PAX6": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT06412718"
				title:  "Validation of Human Drugs Target of Repurposed Drugs and Novel Therapies"
				status: "NOT_YET_RECRUITING"
			},
			{
				nct_id: "NCT06950619"
				title:  "Associations Between Dental Anomalies and Ocular, Cutaneous and Skin Appendages Features"
				status: "NOT_YET_RECRUITING"
			},
		]
	}
	"PAX7": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"PHOX2B": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT03088020"
				title:  "International Congenital Central Hypoventilation Syndrome (CCHS) Registry and CCHS SHARE"
				status: "RECRUITING"
			},
			{
				nct_id: "NCT03568669"
				title:  "Neurocognition in Congenital Central Hypoventilation Syndrome (CCHS)"
				status: "RECRUITING"
			},
		]
	}
	"PLXNA2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"PMEL": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"RAC1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"RARA": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT00105001"
				title:  "Tacrolimus and Mycophenolate Mofetil With or Without Sirolimus in Preventing Acute Graft-Versus-Host Disease in Patients Who Are Undergoing Donor Stem Cell Transplant for Hematologic Cancer"
				status: "COMPLETED"
				phase:  "Phase 2"
			},
		]
	}
	"RET": {
		_in_clinicaltrials: true
		active_trial_count: 12
		clinicaltrials_studies: [
			{
				nct_id: "NCT03045185"
				title:  "Regenerative Endodontic Treatment of Traumatised Teeth"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05517187"
				title:  "Efficacy of Regenerative Endodontic Treatment With PRF as a Secondary Treatment of Mature Necrotic Incisors in Adolescents"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT01424878"
				title:  "Study of Molecular Pathways in Medullary Thyroid Carcinoma and Correlation of Molecular Data With Clinical Behavior of the MTC in Individuals Patients"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05181033"
				title:  "Lenvatinib+Letrozole Versus Fulvestrant in Metastatic ER+/HER2- Breast Cancer, Post Progression on Al + CDK4/6 Inhibitor"
				status: "RECRUITING"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT05581706"
				title:  "Regenerative Endodontics Using Different Intracanal Medicaments on Radiographic Outcomes and Periapical MMP-8 Levels"
				status: "COMPLETED"
			},
		]
	}
	"RHOA": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"RUNX2": {
		_in_clinicaltrials: true
		active_trial_count: 9
		clinicaltrials_studies: [
			{
				nct_id: "NCT06773923"
				title:  "Effectiveness of 3D-printed Patient-specific Resorbable Scaffolds for Maxillary Bone Regeneration"
				status: "ENROLLING_BY_INVITATION"
				phase:  "Phase 3"
			},
			{
				nct_id: "NCT05447026"
				title:  "The Effect of Adjunctive Therapies in Regenerative Treatment of Stage III Grade C Periodontitis"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05791721"
				title:  "Effect of Preemptive Etoricoxib and Dexamethasone on Wound Healing and Clinical Parameters After Third Molar Surgery"
				status: "COMPLETED"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT06856369"
				title:  "Clinical Efficacy of 1% Metformin and Alendronate Gel in Adjunct to Fibrin in Chronic Periodontitis"
				status: "ACTIVE_NOT_RECRUITING"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT05194813"
				title:  "Surface Treatment of the Dental Implant on the Osseointegration"
				status: "COMPLETED"
			},
		]
	}
	"SEMA3A": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SEMA3C": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SHH": {
		_in_clinicaltrials: true
		active_trial_count: 11
		clinicaltrials_studies: [
			{
				nct_id: "NCT01116154"
				title:  "Vorinostat and Lenalidomide in Treating Patients With Relapsed or Refractory Hodgkin Lymphoma or Non-Hodgkin Lymphoma"
				status: "TERMINATED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT01789255"
				title:  "Vorinostat, Tacrolimus, and Methotrexate in Preventing GVHD After Stem Cell Transplant in Patients With Hematological Malignancies"
				status: "COMPLETED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT00601718"
				title:  "Vorinostat, Rituximab, Ifosfamide, Carboplatin, and Etoposide in Treating Patients With Relapsed or Refractory Lymphoma or Previously Untreated T-Cell Non-Hodgkin Lymphoma or Mantle Cell Lymphoma"
				status: "COMPLETED"
				phase:  "Phase 1/Phase 2"
			},
			{
				nct_id: "NCT00499811"
				title:  "Vorinostat in Treating Patients With Metastatic or Unresectable Solid Tumors or Lymphoma and Liver Dysfunction"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT04691414"
				title:  "Retrospective Study Using Next Generation Sequencing (NGS) on Biological Samples to Improve Genetic Counseling for Patients With Previously Explored Craniofacial Midline Defects."
				status: "COMPLETED"
			},
		]
	}
	"SMAD1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SNAI1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SNAI2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SOX10": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SOX2": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT04939051"
				title:  "Obeticholic Acid for Prevention in Barrett's Esophagus"
				status: "RECRUITING"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT06833840"
				title:  "Evaluation of the Expression and Prognostic Role of Tumor Stem Cell Marker SOX2 in Odontogenic Cysts and Tumors"
				status: "COMPLETED"
			},
		]
	}
	"SOX5": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SOX8": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"SOX9": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TBX1": {
		_in_clinicaltrials: true
		active_trial_count: 7
		clinicaltrials_studies: [
			{
				nct_id: "NCT02541058"
				title:  "Non-Invasive Chromosomal Evaluation of 22q11.2"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT01127503"
				title:  "Metyrosine (Demser®) for the Treatment of Psychotic Disorders in Patients With Velocardiofacial Syndrome"
				status: "TERMINATED"
				phase:  "Phase 2"
			},
			{
				nct_id: "NCT00105274"
				title:  "Velocardiofacial (VCFS; 22q11.2; DiGeorge) Syndrome Study"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT00005102"
				title:  "Immunologic Evaluation in Patients With DiGeorge Syndrome or Velocardiofacial Syndrome"
				status: "UNKNOWN"
			},
			{
				nct_id: "NCT05149898"
				title:  "Open-Label Study of ZYN002 Administered as a Transdermal Gel to Children and Adolescents With 22q11.2 Deletion Syndrome"
				status: "COMPLETED"
				phase:  "Phase 1/Phase 2"
			},
		]
	}
	"TBX5": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TCOF1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TFAP2A": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TFAP2B": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TGFBR1": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT07360704"
				title:  "Genotypes and Craniofacial Phenotypes in Orthodontic Patients With Marfan and Loeys-Dietz Syndromes"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT01322165"
				title:  "National Registry of Genetically Triggered Thoracic Aortic Aneurysms and Cardiovascular Conditions"
				status: "COMPLETED"
			},
		]
	}
	"TGFBR2": {
		_in_clinicaltrials: true
		active_trial_count: 2
		clinicaltrials_studies: [
			{
				nct_id: "NCT07360704"
				title:  "Genotypes and Craniofacial Phenotypes in Orthodontic Patients With Marfan and Loeys-Dietz Syndromes"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT01322165"
				title:  "National Registry of Genetically Triggered Thoracic Aortic Aneurysms and Cardiovascular Conditions"
				status: "COMPLETED"
			},
		]
	}
	"TWIST1": {
		_in_clinicaltrials: true
		active_trial_count: 41
		clinicaltrials_studies: [
			{
				nct_id: "NCT03440697"
				title:  "Pathogenetic Basis of Aortopathy and Aortic Valve Disease"
				status: "ACTIVE_NOT_RECRUITING"
			},
			{
				nct_id: "NCT00339846"
				title:  "Genetic Analysis of Craniofrontonasal Syndrome"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT00912119"
				title:  "Amicar Pharmacokinetics of Children Having Craniofacial Surgery"
				status: "COMPLETED"
				phase:  "Phase 1"
			},
			{
				nct_id: "NCT04419363"
				title:  "Burosumab in Children and Adolescents With X-linked Hypophosphatemia"
				status: "UNKNOWN"
				phase:  "Phase 4"
			},
			{
				nct_id: "NCT04072783"
				title:  "Neurodevelopmental Outcomes in Craniosynostosis Repair"
				status: "COMPLETED"
			},
		]
	}
	"TWIST2": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"TYR": {
		_in_clinicaltrials: true
		active_trial_count: 69
		clinicaltrials_studies: [
			{
				nct_id: "NCT00504205"
				title:  "MP470 in Treating Patients With Unresectable or Metastatic Solid Tumor or Lymphoma"
				status: "TERMINATED"
			},
			{
				nct_id: "NCT03653026"
				title:  "A Study of the Efficacy and Safety of Upadacitinib (ABT-494) in Participants With Moderately to Severely Active Ulcerative Colitis"
				status: "COMPLETED"
				phase:  "Phase 3"
			},
			{
				nct_id: "NCT01538342"
				title:  "Role of Tyrosine Kinase Lyn and Cleaved Form by Caspases in Psoriasis"
				status: "COMPLETED"
			},
			{
				nct_id: "NCT05643573"
				title:  "A Study to Learn How Well the Study Treatment Asundexian Works and How Safe it is Compared to Apixaban to Prevent Stroke or Systemic Embolism in People With Irregular and Often Rapid Heartbeat (Atrial Fibrillation), and at Risk for Stroke"
				status: "TERMINATED"
				phase:  "Phase 3"
			},
			{
				nct_id: "NCT03068884"
				title:  "Dopamine Dorsolateral Prefrontal Cortex Behavioural Flexibility"
				status: "COMPLETED"
			},
		]
	}
	"TYRP1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"WNT1": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT02531087"
				title:  "Urinary Biomarkers of OI Pathobiology"
				status: "ACTIVE_NOT_RECRUITING"
			},
		]
	}
	"WNT3A": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
	"ZEB2": {
		_in_clinicaltrials: true
		active_trial_count: 1
		clinicaltrials_studies: [
			{
				nct_id: "NCT05832541"
				title:  "Expression of Epithelial-Mesenchymal Transition Associated Markers in Peri-implant Tissues"
				status: "RECRUITING"
			},
		]
	}
	"ZIC1": {
		_in_clinicaltrials: true
		active_trial_count: 0
	}
}
