package lacuene

// Open Targets: drug target status for neural crest genes.
// Source: Open Targets Platform GraphQL API
// Generated by normalizers/from_opentargets.py -- 91 genes

genes: {
	"ADAM10": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000137845"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"ALDH1A2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000128918"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"AXIN2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000168646"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"BMP2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000125845"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"BMP4": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000125378"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"BMP7": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000101144"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"CDH11": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000140937"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"CDH2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000170558"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"CDH6": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000113361"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"CHD7": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000171316"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"CTNNB1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000168036"
		is_drug_target:     true
		drug_count:         8
		max_clinical_phase: 2
		opentargets_drugs: [
			{
				drug_name: "PRI-724"
				drug_type: "Unknown"
				phase:     2
				disease:   "colorectal adenocarcinoma"
			},
			{
				drug_name: "PRI-724"
				drug_type: "Unknown"
				phase:     2
				disease:   "cirrhosis of liver"
			},
			{
				drug_name: "PRI-724"
				drug_type: "Unknown"
				phase:     1
				disease:   "acute myeloid leukemia"
			},
			{
				drug_name: "PRI-724"
				drug_type: "Unknown"
				phase:     1
				disease:   "chronic myelogenous leukemia"
			},
			{
				drug_name: "PRI-724"
				drug_type: "Unknown"
				phase:     1
				disease:   "neoplasm"
			},
		]
	}
	"CXCR4": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000121966"
		is_drug_target:     true
		drug_count:         128
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "PLERIXAFOR"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute lymphoblastic leukemia"
			},
			{
				drug_name: "PLERIXAFOR"
				drug_type: "Small molecule"
				phase:     4
				disease:   "lymphoma"
			},
			{
				drug_name: "PLERIXAFOR"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "PLERIXAFOR"
				drug_type: "Small molecule"
				phase:     4
				disease:   "lymphoma"
			},
			{
				drug_name: "PLERIXAFOR"
				drug_type: "Small molecule"
				phase:     4
				disease:   "multiple myeloma"
			},
		]
	}
	"DLL1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000198719"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"DLX2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000115844"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"DLX3": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000064195"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"DLX5": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000105880"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"DLX6": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000006377"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"ECE1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000117298"
		is_drug_target:     true
		drug_count:         1
		max_clinical_phase: 2
		opentargets_drugs: [
			{
				drug_name: "DAGLUTRIL"
				drug_type: "Small molecule"
				phase:     2
				disease:   "hypertension"
			},
		]
	}
	"EDN1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000078401"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"EDN3": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000124205"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"EDNRA": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000151617"
		is_drug_target:     true
		drug_count:         176
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "MACITENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "AMBRISENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
		]
	}
	"EDNRB": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000136160"
		is_drug_target:     true
		drug_count:         122
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "AMBRISENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "SITAXENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
			{
				drug_name: "BOSENTAN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "hypertension"
			},
		]
	}
	"ERBB3": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000065361"
		is_drug_target:     true
		drug_count:         168
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "thyroid carcinoma"
			},
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "thyroid neoplasm"
			},
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "thyroid cancer"
			},
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "medullary thyroid gland carcinoma"
			},
		]
	}
	"ETS1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000134954"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"EVC": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000072840"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"FGF8": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000107831"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"FGFR1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000077782"
		is_drug_target:     true
		drug_count:         655
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "FUTIBATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "INFIGRATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "REGORAFENIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "NINTEDANIB ESYLATE"
				drug_type: "Small molecule"
				phase:     4
				disease:   "systemic scleroderma"
			},
			{
				drug_name: "ERDAFITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
		]
	}
	"FGFR2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000066468"
		is_drug_target:     true
		drug_count:         458
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "ERDAFITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "FUTIBATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "PEMIGATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "INFIGRATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "REGORAFENIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
		]
	}
	"FGFR3": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000068078"
		is_drug_target:     true
		drug_count:         550
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "ERDAFITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "PEMIGATINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "PAZOPANIB HYDROCHLORIDE"
				drug_type: "Small molecule"
				phase:     4
				disease:   "sarcoma"
			},
			{
				drug_name: "PAZOPANIB HYDROCHLORIDE"
				drug_type: "Small molecule"
				phase:     4
				disease:   "renal cell carcinoma"
			},
			{
				drug_name: "NINTEDANIB ESYLATE"
				drug_type: "Small molecule"
				phase:     4
				disease:   "systemic scleroderma"
			},
		]
	}
	"FN1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000115414"
		is_drug_target:     true
		drug_count:         23
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "OCRIPLASMIN"
				drug_type: "Protein"
				phase:     4
				disease:   "eye disease"
			},
			{
				drug_name: "OCRIPLASMIN"
				drug_type: "Protein"
				phase:     4
				disease:   "Abnormal retinal morphology"
			},
			{
				drug_name: "L19IL2"
				drug_type: "Unknown"
				phase:     3
				disease:   "melanoma"
			},
			{
				drug_name: "OCRIPLASMIN"
				drug_type: "Protein"
				phase:     3
				disease:   "macular holes"
			},
			{
				drug_name: "L19TNFA"
				drug_type: "Unknown"
				phase:     2
				disease:   "leiomyosarcoma"
			},
		]
	}
	"FOXD3": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000187140"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"GATA4": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000136574"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"GBX2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000168505"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"GDNF": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000168621"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"GFRA1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000151892"
		is_drug_target:     true
		drug_count:         1
		max_clinical_phase: 1
		opentargets_drugs: [
			{
				drug_name: "LIATERMIN"
				drug_type: "Protein"
				phase:     1
				disease:   "Parkinson disease"
			},
		]
	}
	"HAND1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000113196"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"HAND2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000164107"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"IRF6": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000117595"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"ITGB1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000150093"
		is_drug_target:     true
		drug_count:         15
		max_clinical_phase: 2
		opentargets_drugs: [
			{
				drug_name: "VOLOCIXIMAB"
				drug_type: "Antibody"
				phase:     2
				disease:   "renal cell carcinoma"
			},
			{
				drug_name: "VOLOCIXIMAB"
				drug_type: "Antibody"
				phase:     2
				disease:   "melanoma"
			},
			{
				drug_name: "VOLOCIXIMAB"
				drug_type: "Antibody"
				phase:     2
				disease:   "melanoma"
			},
			{
				drug_name: "ATN-161"
				drug_type: "Protein"
				phase:     2
				disease:   "renal cell carcinoma"
			},
			{
				drug_name: "VOLOCIXIMAB"
				drug_type: "Antibody"
				phase:     2
				disease:   "pancreatic carcinoma"
			},
		]
	}
	"JAG1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000101384"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"KIT": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000157404"
		is_drug_target:     true
		drug_count:         2349
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "DASATINIB ANHYDROUS"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute lymphoblastic leukemia"
			},
			{
				drug_name: "MIDOSTAURIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute myeloid leukemia"
			},
			{
				drug_name: "DASATINIB ANHYDROUS"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute lymphoblastic leukemia"
			},
			{
				drug_name: "DASATINIB ANHYDROUS"
				drug_type: "Small molecule"
				phase:     4
				disease:   "chronic myelogenous leukemia"
			},
			{
				drug_name: "DASATINIB ANHYDROUS"
				drug_type: "Small molecule"
				phase:     4
				disease:   "chronic myelogenous leukemia"
			},
		]
	}
	"LEF1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000138795"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"MEF2C": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000081189"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"MITF": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000187098"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"MMP2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000087245"
		is_drug_target:     true
		drug_count:         9
		max_clinical_phase: 3
		opentargets_drugs: [
			{
				drug_name: "MARIMASTAT"
				drug_type: "Small molecule"
				phase:     3
				disease:   "breast cancer"
			},
			{
				drug_name: "MARIMASTAT"
				drug_type: "Small molecule"
				phase:     3
				disease:   "lung cancer"
			},
			{
				drug_name: "REBIMASTAT"
				drug_type: "Small molecule"
				phase:     2
				disease:   "prostate adenocarcinoma"
			},
			{
				drug_name: "CTS-1027"
				drug_type: "Small molecule"
				phase:     2
				disease:   "hepatitis C virus infection"
			},
			{
				drug_name: "CTS-1027"
				drug_type: "Small molecule"
				phase:     2
				disease:   "hepatitis C virus infection"
			},
		]
	}
	"MMP9": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000100985"
		is_drug_target:     true
		drug_count:         20
		max_clinical_phase: 3
		opentargets_drugs: [
			{
				drug_name: "ANDECALIXIMAB"
				drug_type: "Antibody"
				phase:     3
				disease:   "gastric adenocarcinoma"
			},
			{
				drug_name: "MARIMASTAT"
				drug_type: "Small molecule"
				phase:     3
				disease:   "breast cancer"
			},
			{
				drug_name: "MARIMASTAT"
				drug_type: "Small molecule"
				phase:     3
				disease:   "lung cancer"
			},
			{
				drug_name: "AZD-1236"
				drug_type: "Small molecule"
				phase:     2
				disease:   "chronic obstructive pulmonary disease"
			},
			{
				drug_name: "ANDECALIXIMAB"
				drug_type: "Antibody"
				phase:     2
				disease:   "Crohn's disease"
			},
		]
	}
	"MSX1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000163132"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"MSX2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000120149"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"MYCN": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000134323"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NF1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000196712"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NGFR": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000064300"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NKX2-5": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000183072"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NOTCH1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000148400"
		is_drug_target:     true
		drug_count:         3
		max_clinical_phase: 1
		opentargets_drugs: [
			{
				drug_name: "BRONTICTUZUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "neoplasm"
			},
			{
				drug_name: "BRONTICTUZUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "cancer"
			},
			{
				drug_name: "BRONTICTUZUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "metastatic colorectal cancer"
			},
		]
	}
	"NOTCH2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000134250"
		is_drug_target:     true
		drug_count:         3
		max_clinical_phase: 1
		opentargets_drugs: [
			{
				drug_name: "TAREXTUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "neoplasm"
			},
			{
				drug_name: "TAREXTUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "small cell lung carcinoma"
			},
			{
				drug_name: "TAREXTUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "pancreatic carcinoma"
			},
		]
	}
	"NR2F1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000175745"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NR2F2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000185551"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"NRP1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000099250"
		is_drug_target:     true
		drug_count:         1
		max_clinical_phase: 1
		opentargets_drugs: [
			{
				drug_name: "VESENCUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "cancer"
			},
		]
	}
	"PAX7": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000009709"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"PHOX2B": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000109132"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"PLXNA2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000076356"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"PMEL": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000185664"
		is_drug_target:     true
		drug_count:         12
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "TEBENTAFUSP"
				drug_type: "Protein"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "TEBENTAFUSP"
				drug_type: "Protein"
				phase:     4
				disease:   "melanoma"
			},
			{
				drug_name: "TEBENTAFUSP"
				drug_type: "Protein"
				phase:     4
				disease:   "uveal cancer"
			},
			{
				drug_name: "TEBENTAFUSP"
				drug_type: "Protein"
				phase:     3
				disease:   "Uveal Melanoma"
			},
			{
				drug_name: "TEBENTAFUSP"
				drug_type: "Protein"
				phase:     2
				disease:   "melanoma"
			},
		]
	}
	"RAC1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000136238"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"RARA": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000131759"
		is_drug_target:     true
		drug_count:         286
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "TRETINOIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute promyelocytic leukemia"
			},
			{
				drug_name: "TRETINOIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute promyelocytic leukemia"
			},
			{
				drug_name: "TRETINOIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "acute promyelocytic leukemia"
			},
			{
				drug_name: "ACITRETIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "psoriasis"
			},
			{
				drug_name: "ACITRETIN"
				drug_type: "Small molecule"
				phase:     4
				disease:   "psoriasis"
			},
		]
	}
	"RET": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000165731"
		is_drug_target:     true
		drug_count:         1124
		max_clinical_phase: 4
		opentargets_drugs: [
			{
				drug_name: "VANDETANIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "ALECTINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "neoplasm"
			},
			{
				drug_name: "SUNITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "renal cell carcinoma"
			},
			{
				drug_name: "SUNITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "renal cell carcinoma"
			},
			{
				drug_name: "SUNITINIB"
				drug_type: "Small molecule"
				phase:     4
				disease:   "renal cell carcinoma"
			},
		]
	}
	"RHOA": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000067560"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"RUNX2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000124813"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SEMA3A": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000075213"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SEMA3C": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000075223"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SHH": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000164690"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SMAD1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000170365"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SNAI1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000124216"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SNAI2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000019549"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SOX10": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000100146"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SOX2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000181449"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SOX5": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000134532"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SOX8": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000005513"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"SOX9": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000125398"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TBX1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000184058"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TBX5": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000089225"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TCOF1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000070814"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TFAP2A": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000137203"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TGFBR1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000106799"
		is_drug_target:     true
		drug_count:         30
		max_clinical_phase: 2
		opentargets_drugs: [
			{
				drug_name: "GALUNISERTIB"
				drug_type: "Small molecule"
				phase:     2
				disease:   "hepatocellular carcinoma"
			},
			{
				drug_name: "GALUNISERTIB"
				drug_type: "Small molecule"
				phase:     2
				disease:   "myelodysplastic syndrome"
			},
			{
				drug_name: "GALUNISERTIB"
				drug_type: "Small molecule"
				phase:     2
				disease:   "glioblastoma multiforme"
			},
			{
				drug_name: "VACTOSERTIB"
				drug_type: "Small molecule"
				phase:     2
				disease:   "non-small cell lung carcinoma"
			},
			{
				drug_name: "VACTOSERTIB"
				drug_type: "Small molecule"
				phase:     2
				disease:   "stomach neoplasm"
			},
		]
	}
	"TGFBR2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000163513"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TWIST1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000122691"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TWIST2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000233608"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"TYR": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000077498"
		is_drug_target:     true
		drug_count:         1
		max_clinical_phase: 2
		opentargets_drugs: [
			{
				drug_name: "ARBUTIN"
				drug_type: "Small molecule"
				phase:     2
				disease:   "freckles"
			},
		]
	}
	"TYRP1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000107165"
		is_drug_target:     true
		drug_count:         1
		max_clinical_phase: 1
		opentargets_drugs: [
			{
				drug_name: "FLANVOTUMAB"
				drug_type: "Antibody"
				phase:     1
				disease:   "melanoma"
			},
		]
	}
	"WNT1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000125084"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"WNT3A": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000154342"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"ZEB2": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000169554"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
	"ZIC1": {
		_in_opentargets: true
		opentargets_id:  "ENSG00000152977"
		is_drug_target:     false
		drug_count:         0
		max_clinical_phase: 0
	}
}
