package froq

// STRING: protein-protein interaction data for neural crest genes.
// Source: STRING database (string-db.org) v12
// Generated by normalizers/from_string.py -- 95 genes

genes: {
	"ADAM10": {
		_in_string: true
		string_id:  "9606.ENSP00000260408"
		string_interaction_count: 1
		string_partners: ["NOTCH1"]
	}
	"ALDH1A2": {
		_in_string: true
		string_id:  "9606.ENSP00000249750"
		string_interaction_count: 0
	}
	"AXIN2": {
		_in_string: true
		string_id:  "9606.ENSP00000302625"
		string_interaction_count: 1
		string_partners: ["CTNNB1"]
	}
	"BMP2": {
		_in_string: true
		string_id:  "9606.ENSP00000368104"
		string_interaction_count: 0
	}
	"BMP4": {
		_in_string: true
		string_id:  "9606.ENSP00000245451"
		string_interaction_count: 2
		string_partners: ["BMP7", "BMP2"]
	}
	"BMP7": {
		_in_string: true
		string_id:  "9606.ENSP00000379204"
		string_interaction_count: 1
		string_partners: ["BMP2"]
	}
	"CDH11": {
		_in_string: true
		string_id:  "9606.ENSP00000268603"
		string_interaction_count: 2
		string_partners: ["CTNNB1", "CDH2"]
	}
	"CDH2": {
		_in_string: true
		string_id:  "9606.ENSP00000269141"
		string_interaction_count: 3
		string_partners: ["CTNNB1", "CDH11", "FGFR1"]
	}
	"CDH6": {
		_in_string: true
		string_id:  "9606.ENSP00000265071"
		string_interaction_count: 2
		string_partners: ["CTNNB1", "CDH2"]
	}
	"CHD7": {
		_in_string: true
		string_id:  "9606.ENSP00000392028"
		string_interaction_count: 1
		string_partners: ["SOX2"]
	}
	"CTNNB1": {
		_in_string: true
		string_id:  "9606.ENSP00000495360"
		string_interaction_count: 0
	}
	"CXCR4": {
		_in_string: true
		string_id:  "9606.ENSP00000386884"
		string_interaction_count: 0
	}
	"DCT": {
		_in_string: true
		string_id:  "9606.ENSP00000392762"
		string_interaction_count: 5
		string_partners: ["TYR", "MITF", "PMEL", "SOX10", "PAX3"]
	}
	"DLL1": {
		_in_string: true
		string_id:  "9606.ENSP00000355718"
		string_interaction_count: 2
		string_partners: ["NOTCH2", "NOTCH1"]
	}
	"DLX2": {
		_in_string: true
		string_id:  "9606.ENSP00000234198"
		string_interaction_count: 2
		string_partners: ["PAX6", "BMP4"]
	}
	"DLX3": {
		_in_string: true
		string_id:  "9606.ENSP00000389870"
		string_interaction_count: 1
		string_partners: ["RUNX2"]
	}
	"DLX5": {
		_in_string: true
		string_id:  "9606.ENSP00000498116"
		string_interaction_count: 6
		string_partners: ["RUNX2", "DLX6", "BMP2", "MSX2", "WNT3A", "BMP7"]
	}
	"DLX6": {
		_in_string: true
		string_id:  "9606.ENSP00000428480"
		string_interaction_count: 3
		string_partners: ["DLX5", "RUNX2", "BMP2"]
	}
	"ECE1": {
		_in_string: true
		string_id:  "9606.ENSP00000364028"
		string_interaction_count: 4
		string_partners: ["EDN1", "EDN3", "EDNRA", "EDNRB"]
	}
	"EDN1": {
		_in_string: true
		string_id:  "9606.ENSP00000368683"
		string_interaction_count: 6
		string_partners: ["EDNRA", "EDNRB", "ECE1", "EDN3", "MMP9", "MMP2"]
	}
	"EDN3": {
		_in_string: true
		string_id:  "9606.ENSP00000337128"
		string_interaction_count: 6
		string_partners: ["EDNRA", "EDNRB", "EDN1", "ECE1", "SOX10", "GDNF"]
	}
	"EDNRA": {
		_in_string: true
		string_id:  "9606.ENSP00000315011"
		string_interaction_count: 3
		string_partners: ["EDN3", "EDN1", "EDNRB"]
	}
	"EDNRB": {
		_in_string: true
		string_id:  "9606.ENSP00000366416"
		string_interaction_count: 3
		string_partners: ["EDN3", "EDN1", "EDNRA"]
	}
	"ERBB3": {
		_in_string: true
		string_id:  "9606.ENSP00000267101"
		string_interaction_count: 0
	}
	"ETS1": {
		_in_string: true
		string_id:  "9606.ENSP00000376436"
		string_interaction_count: 0
	}
	"EVC": {
		_in_string: true
		string_id:  "9606.ENSP00000264956"
		string_interaction_count: 0
	}
	"FGF8": {
		_in_string: true
		string_id:  "9606.ENSP00000321797"
		string_interaction_count: 4
		string_partners: ["FGFR3", "FGFR1", "FGFR2", "SHH"]
	}
	"FGFR1": {
		_in_string: true
		string_id:  "9606.ENSP00000393312"
		string_interaction_count: 0
	}
	"FGFR2": {
		_in_string: true
		string_id:  "9606.ENSP00000410294"
		string_interaction_count: 1
		string_partners: ["FGF8"]
	}
	"FGFR3": {
		_in_string: true
		string_id:  "9606.ENSP00000339824"
		string_interaction_count: 2
		string_partners: ["FGF8", "FGFR2"]
	}
	"FN1": {
		_in_string: true
		string_id:  "9606.ENSP00000346839"
		string_interaction_count: 1
		string_partners: ["ITGB1"]
	}
	"FOXD3": {
		_in_string: true
		string_id:  "9606.ENSP00000360157"
		string_interaction_count: 5
		string_partners: ["SOX2", "SOX10", "SNAI2", "SOX9", "PAX3"]
	}
	"GATA4": {
		_in_string: true
		string_id:  "9606.ENSP00000435712"
		string_interaction_count: 4
		string_partners: ["NKX2-5", "TBX5", "HAND2", "SOX9"]
	}
	"GBX2": {
		_in_string: true
		string_id:  "9606.ENSP00000302251"
		string_interaction_count: 3
		string_partners: ["WNT1", "FGF8", "SHH"]
	}
	"GDNF": {
		_in_string: true
		string_id:  "9606.ENSP00000409007"
		string_interaction_count: 2
		string_partners: ["GFRA1", "RET"]
	}
	"GFRA1": {
		_in_string: true
		string_id:  "9606.ENSP00000347591"
		string_interaction_count: 3
		string_partners: ["RET", "GDNF", "EDNRB"]
	}
	"HAND1": {
		_in_string: true
		string_id:  "9606.ENSP00000231121"
		string_interaction_count: 1
		string_partners: ["NKX2-5"]
	}
	"HAND2": {
		_in_string: true
		string_id:  "9606.ENSP00000352565"
		string_interaction_count: 6
		string_partners: ["GATA4", "NKX2-5", "TBX5", "RUNX2", "MEF2C", "PHOX2B"]
	}
	"IRF6": {
		_in_string: true
		string_id:  "9606.ENSP00000355988"
		string_interaction_count: 1
		string_partners: ["MSX1"]
	}
	"ITGB1": {
		_in_string: true
		string_id:  "9606.ENSP00000379350"
		string_interaction_count: 1
		string_partners: ["FN1"]
	}
	"JAG1": {
		_in_string: true
		string_id:  "9606.ENSP00000254958"
		string_interaction_count: 2
		string_partners: ["NOTCH2", "NOTCH1"]
	}
	"KIT": {
		_in_string: true
		string_id:  "9606.ENSP00000288135"
		string_interaction_count: 0
	}
	"LEF1": {
		_in_string: true
		string_id:  "9606.ENSP00000265165"
		string_interaction_count: 1
		string_partners: ["CTNNB1"]
	}
	"MEF2C": {
		_in_string: true
		string_id:  "9606.ENSP00000340874"
		string_interaction_count: 3
		string_partners: ["NKX2-5", "GATA4", "CTNNB1"]
	}
	"MITF": {
		_in_string: true
		string_id:  "9606.ENSP00000391803"
		string_interaction_count: 4
		string_partners: ["TYR", "DCT", "SOX10", "TYRP1"]
	}
	"MMP2": {
		_in_string: true
		string_id:  "9606.ENSP00000219070"
		string_interaction_count: 0
	}
	"MMP9": {
		_in_string: true
		string_id:  "9606.ENSP00000361405"
		string_interaction_count: 0
	}
	"MSX1": {
		_in_string: true
		string_id:  "9606.ENSP00000372170"
		string_interaction_count: 4
		string_partners: ["MSX2", "BMP4", "LEF1", "IRF6"]
	}
	"MSX2": {
		_in_string: true
		string_id:  "9606.ENSP00000239243"
		string_interaction_count: 7
		string_partners: ["RUNX2", "MSX1", "TWIST1", "DLX5", "BMP4", "FGFR3", "FGFR2"]
	}
	"MYCN": {
		_in_string: true
		string_id:  "9606.ENSP00000281043"
		string_interaction_count: 0
	}
	"NF1": {
		_in_string: true
		string_id:  "9606.ENSP00000351015"
		string_interaction_count: 0
	}
	"NGFR": {
		_in_string: true
		string_id:  "9606.ENSP00000172229"
		string_interaction_count: 0
	}
	"NKX2-5": {
		_in_string: true
		string_id:  "9606.ENSP00000327758"
		string_interaction_count: 4
		string_partners: ["TBX5", "GATA4", "MEF2C", "HAND2"]
	}
	"NOTCH1": {
		_in_string: true
		string_id:  "9606.ENSP00000498587"
		string_interaction_count: 2
		string_partners: ["JAG1", "DLL1"]
	}
	"NOTCH2": {
		_in_string: true
		string_id:  "9606.ENSP00000256646"
		string_interaction_count: 2
		string_partners: ["JAG1", "DLL1"]
	}
	"NR2F1": {
		_in_string: true
		string_id:  "9606.ENSP00000325819"
		string_interaction_count: 0
	}
	"NR2F2": {
		_in_string: true
		string_id:  "9606.ENSP00000377721"
		string_interaction_count: 1
		string_partners: ["MEF2C"]
	}
	"NRP1": {
		_in_string: true
		string_id:  "9606.ENSP00000265371"
		string_interaction_count: 3
		string_partners: ["SEMA3A", "PLXNA2", "SEMA3C"]
	}
	"PAX3": {
		_in_string: true
		string_id:  "9606.ENSP00000375921"
		string_interaction_count: 3
		string_partners: ["SOX10", "PAX7", "MITF"]
	}
	"PAX6": {
		_in_string: true
		string_id:  "9606.ENSP00000492024"
		string_interaction_count: 2
		string_partners: ["SOX2", "MITF"]
	}
	"PAX7": {
		_in_string: true
		string_id:  "9606.ENSP00000364524"
		string_interaction_count: 3
		string_partners: ["PAX3", "SOX10", "SNAI2"]
	}
	"PHOX2B": {
		_in_string: true
		string_id:  "9606.ENSP00000226382"
		string_interaction_count: 5
		string_partners: ["HAND2", "EDN3", "RET", "GDNF", "EDNRB"]
	}
	"PLXNA2": {
		_in_string: true
		string_id:  "9606.ENSP00000356000"
		string_interaction_count: 3
		string_partners: ["SEMA3A", "NRP1", "SEMA3C"]
	}
	"PMEL": {
		_in_string: true
		string_id:  "9606.ENSP00000402758"
		string_interaction_count: 3
		string_partners: ["TYR", "TYRP1", "DCT"]
	}
	"RAC1": {
		_in_string: true
		string_id:  "9606.ENSP00000348461"
		string_interaction_count: 0
	}
	"RARA": {
		_in_string: true
		string_id:  "9606.ENSP00000254066"
		string_interaction_count: 0
	}
	"RET": {
		_in_string: true
		string_id:  "9606.ENSP00000347942"
		string_interaction_count: 2
		string_partners: ["GFRA1", "GDNF"]
	}
	"RHOA": {
		_in_string: true
		string_id:  "9606.ENSP00000400175"
		string_interaction_count: 0
	}
	"RUNX2": {
		_in_string: true
		string_id:  "9606.ENSP00000360493"
		string_interaction_count: 4
		string_partners: ["MSX2", "DLX5", "BMP2", "SOX9"]
	}
	"SEMA3A": {
		_in_string: true
		string_id:  "9606.ENSP00000265362"
		string_interaction_count: 2
		string_partners: ["PLXNA2", "NRP1"]
	}
	"SEMA3C": {
		_in_string: true
		string_id:  "9606.ENSP00000265361"
		string_interaction_count: 2
		string_partners: ["NRP1", "PLXNA2"]
	}
	"SHH": {
		_in_string: true
		string_id:  "9606.ENSP00000297261"
		string_interaction_count: 0
	}
	"SMAD1": {
		_in_string: true
		string_id:  "9606.ENSP00000305769"
		string_interaction_count: 0
	}
	"SNAI1": {
		_in_string: true
		string_id:  "9606.ENSP00000244050"
		string_interaction_count: 0
	}
	"SNAI2": {
		_in_string: true
		string_id:  "9606.ENSP00000020945"
		string_interaction_count: 4
		string_partners: ["TWIST1", "SOX9", "CDH2", "SNAI1"]
	}
	"SOX10": {
		_in_string: true
		string_id:  "9606.ENSP00000380093"
		string_interaction_count: 2
		string_partners: ["PAX3", "MITF"]
	}
	"SOX2": {
		_in_string: true
		string_id:  "9606.ENSP00000323588"
		string_interaction_count: 2
		string_partners: ["CTNNB1", "PAX6"]
	}
	"SOX5": {
		_in_string: true
		string_id:  "9606.ENSP00000398273"
		string_interaction_count: 2
		string_partners: ["SOX9", "CTNNB1"]
	}
	"SOX8": {
		_in_string: true
		string_id:  "9606.ENSP00000293894"
		string_interaction_count: 0
	}
	"SOX9": {
		_in_string: true
		string_id:  "9606.ENSP00000245479"
		string_interaction_count: 3
		string_partners: ["CTNNB1", "RUNX2", "GATA4"]
	}
	"TBX1": {
		_in_string: true
		string_id:  "9606.ENSP00000331791"
		string_interaction_count: 1
		string_partners: ["NKX2-5"]
	}
	"TBX5": {
		_in_string: true
		string_id:  "9606.ENSP00000309913"
		string_interaction_count: 5
		string_partners: ["NKX2-5", "GATA4", "CTNNB1", "MEF2C", "HAND2"]
	}
	"TCOF1": {
		_in_string: true
		string_id:  "9606.ENSP00000367028"
		string_interaction_count: 0
	}
	"TFAP2A": {
		_in_string: true
		string_id:  "9606.ENSP00000501092"
		string_interaction_count: 1
		string_partners: ["TFAP2B"]
	}
	"TFAP2B": {
		_in_string: true
		string_id:  "9606.ENSP00000377265"
		string_interaction_count: 2
		string_partners: ["TFAP2A", "KIT"]
	}
	"TGFBR1": {
		_in_string: true
		string_id:  "9606.ENSP00000447297"
		string_interaction_count: 1
		string_partners: ["TGFBR2"]
	}
	"TGFBR2": {
		_in_string: true
		string_id:  "9606.ENSP00000351905"
		string_interaction_count: 1
		string_partners: ["TGFBR1"]
	}
	"TWIST1": {
		_in_string: true
		string_id:  "9606.ENSP00000242261"
		string_interaction_count: 5
		string_partners: ["RUNX2", "SNAI2", "TWIST2", "MSX2", "SNAI1"]
	}
	"TWIST2": {
		_in_string: true
		string_id:  "9606.ENSP00000482581"
		string_interaction_count: 5
		string_partners: ["RUNX2", "TWIST1", "SNAI1", "SNAI2", "ZEB2"]
	}
	"TYR": {
		_in_string: true
		string_id:  "9606.ENSP00000263321"
		string_interaction_count: 3
		string_partners: ["PMEL", "MITF", "DCT"]
	}
	"TYRP1": {
		_in_string: true
		string_id:  "9606.ENSP00000373570"
		string_interaction_count: 3
		string_partners: ["MITF", "PMEL", "TYR"]
	}
	"WNT1": {
		_in_string: true
		string_id:  "9606.ENSP00000293549"
		string_interaction_count: 0
	}
	"WNT3A": {
		_in_string: true
		string_id:  "9606.ENSP00000284523"
		string_interaction_count: 1
		string_partners: ["CTNNB1"]
	}
	"ZEB2": {
		_in_string: true
		string_id:  "9606.ENSP00000487174"
		string_interaction_count: 1
		string_partners: ["TWIST1"]
	}
	"ZIC1": {
		_in_string: true
		string_id:  "9606.ENSP00000282928"
		string_interaction_count: 2
		string_partners: ["PAX3", "CTNNB1"]
	}
}
