#!/usr/bin/env python3
"""
Normalizer: NIH Reporter -> model/nih_reporter.cue

Queries the NIH Reporter v2 API for active craniofacial grants mentioning
each neural crest gene. Extracts project numbers, titles, PIs, and orgs.

Results are cached in data/nih_reporter/nih_reporter_cache.json.

Usage:
    python3 normalizers/from_nih_reporter.py
"""

import json
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "normalizers"))

from genes import GENES
from pipeline import PipelineReport, escape_cue_string
from utils import post_json_with_retry

CACHE_DIR = REPO_ROOT / "data" / "nih_reporter"
CACHE_FILE = CACHE_DIR / "nih_reporter_cache.json"
OUTPUT_FILE = REPO_ROOT / "model" / "nih_reporter.cue"

API_URL = "https://api.reporter.nih.gov/v2/projects/search"

REQUEST_DELAY = 0.35


def fetch_projects(symbol: str) -> dict | None:
    """
    Query NIH Reporter for active craniofacial grants mentioning a gene.
    Returns dict with:
      - active_grant_count: int
      - projects: list of {project_num, project_title, pi_name, org_name, fiscal_year}
    Or None on failure.
    """
    payload = {
        "criteria": {
            "advanced_text_search": {
                "operator": "and",
                "search_field": "terms",
                "search_text": f"{symbol} craniofacial",
            },
            "is_active": True,
        },
        "limit": 10,
        "offset": 0,
    }

    try:
        data = post_json_with_retry(
            API_URL,
            json_body=payload,
            headers={"Accept": "application/json"},
        )
    except Exception as e:
        print(f"  WARNING: request failed: {e}", file=sys.stderr)
        return None

    results = data.get("results", [])
    meta = data.get("meta", {})
    total = meta.get("total", len(results))

    projects = []
    for r in results:
        project_num = r.get("project_num", "")
        project_title = r.get("project_title", "")
        fiscal_year = r.get("fiscal_year")

        # PI name: contact_pi_name or first from principal_investigators list
        pi_name = r.get("contact_pi_name", "")
        if not pi_name:
            pis = r.get("principal_investigators", [])
            if pis and isinstance(pis, list):
                pi = pis[0]
                if isinstance(pi, dict):
                    pi_name = pi.get("full_name", "") or pi.get("profile_name", "")

        org_name = ""
        org = r.get("organization", {})
        if isinstance(org, dict):
            org_name = org.get("org_name", "")

        if project_num:
            projects.append({
                "project_num": project_num.strip(),
                "project_title": (project_title or "").strip(),
                "pi_name": (pi_name or "").strip(),
                "org_name": (org_name or "").strip(),
                "fiscal_year": fiscal_year,
            })

    return {"active_grant_count": total, "projects": projects}


def load_cache() -> dict:
    """Load cached NIH Reporter data if available."""
    if CACHE_FILE.exists():
        with open(CACHE_FILE) as f:
            return json.load(f)
    return {}


def save_cache(cache: dict) -> None:
    """Persist the NIH Reporter cache to disk."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f, indent=2, sort_keys=True)


def generate_cue(reporter_data: dict) -> str:
    """Generate CUE source from NIH Reporter data, keyed by HGNC symbol."""
    lines = [
        "package froq",
        "",
        "// NIH Reporter: active craniofacial grant data for neural crest genes.",
        "// Source: NIH Reporter v2 API (projects/search)",
        f"// Generated by normalizers/from_nih_reporter.py -- {len(reporter_data)} genes",
        "",
        "genes: {",
    ]

    for symbol in sorted(reporter_data.keys()):
        entry = reporter_data[symbol]
        grant_count = entry["active_grant_count"]
        projects = entry.get("projects", [])

        lines.append(f'\t"{symbol}": {{')
        lines.append(f"\t\t_in_nih_reporter:   true")
        lines.append(f"\t\tactive_grant_count: {grant_count}")

        if projects:
            lines.append(f"\t\tnih_reporter_projects: [")
            for p in projects:
                pnum = escape_cue_string(p["project_num"])
                ptitle = escape_cue_string(p["project_title"])
                pi = escape_cue_string(p.get("pi_name", ""))
                org = escape_cue_string(p.get("org_name", ""))
                fy = p.get("fiscal_year")

                lines.append(f"\t\t\t{{")
                lines.append(f'\t\t\t\tproject_num:   "{pnum}"')
                lines.append(f'\t\t\t\tproject_title: "{ptitle}"')
                if pi:
                    lines.append(f'\t\t\t\tpi_name:       "{pi}"')
                if org:
                    lines.append(f'\t\t\t\torg_name:      "{org}"')
                if fy is not None:
                    lines.append(f"\t\t\t\tfiscal_year:   {fy}")
                lines.append(f"\t\t\t}},")
            lines.append(f"\t\t]")

        lines.append(f"\t}}")

    lines.append("}")
    lines.append("")  # trailing newline

    return "\n".join(lines)


def main():
    report = PipelineReport("from_nih_reporter")
    print(f"from_nih_reporter: querying NIH Reporter for {len(GENES)} genes...")

    cache = load_cache()
    reporter_data = {}
    fetched = 0

    for symbol in sorted(GENES.keys()):
        if symbol in cache:
            cached_count = cache[symbol]["active_grant_count"]
            print(f"  {symbol}: cached ({cached_count} grants)")
            reporter_data[symbol] = cache[symbol]
            report.cached(symbol, f"{cached_count} grants")
            continue

        print(f"  {symbol}: querying NIH Reporter...", end=" ", flush=True)
        result = fetch_projects(symbol)
        time.sleep(REQUEST_DELAY)

        if result is None:
            print("FAILED")
            report.failed(symbol, "API request failed")
            continue

        grant_count = result["active_grant_count"]
        proj_count = len(result["projects"])
        print(f"{grant_count} grants, {proj_count} projects returned")

        reporter_data[symbol] = result
        cache[symbol] = result
        report.ok(symbol, f"{grant_count} grants")
        fetched += 1

    # Save updated cache
    save_cache(cache)

    if not reporter_data:
        print("ERROR: no NIH Reporter data retrieved for any gene", file=sys.stderr)
        sys.exit(1)

    # Write CUE output
    cue_source = generate_cue(reporter_data)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(cue_source)

    total_grants = sum(d["active_grant_count"] for d in reporter_data.values())
    total_projects = sum(len(d.get("projects", [])) for d in reporter_data.values())

    print(f"from_nih_reporter: wrote {OUTPUT_FILE}")
    print(f"  {len(reporter_data)} genes, {total_grants} total active grants, "
          f"{total_projects} project records")
    print(report.summary())


if __name__ == "__main__":
    main()
