#!/usr/bin/env python3
"""
Normalizer: Model Organisms (MGI + ZFIN) -> model/models.cue

Queries the NCBI Datasets ortholog API for each of the 95 neural crest genes
to determine mouse (Mus musculus) and zebrafish (Danio rerio) ortholog
availability — a proxy for model organism research resources.

Results are cached in data/models/models_cache.json for reproducibility.

Usage:
    python3 normalizers/from_models.py
"""

import json
import sys
import time
from pathlib import Path

# Resolve paths relative to repo root (parent of normalizers/)
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "normalizers"))

from genes import GENES
from pipeline import PipelineReport, escape_cue_string
from utils import fetch_json_with_retry

CACHE_DIR = REPO_ROOT / "data" / "models"
CACHE_FILE = CACHE_DIR / "models_cache.json"
OUTPUT_FILE = REPO_ROOT / "model" / "models.cue"

# NCBI Datasets v2 ortholog API
NCBI_ORTHOLOGS_URL = "https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/{gene_id}/orthologs"

# Taxonomy IDs for model organisms
MOUSE_TAXID = 10090   # Mus musculus
ZEBRAFISH_TAXID = 7955  # Danio rerio

REQUEST_DELAY = 0.5  # seconds between requests


def fetch_model_organisms(symbol: str, ncbi_id: str) -> dict | None:
    """
    Query NCBI Datasets ortholog API for a gene's NCBI ID.
    Returns dict with mouse and zebrafish ortholog counts, or None on failure.
    """
    url = NCBI_ORTHOLOGS_URL.format(gene_id=ncbi_id)

    try:
        data = fetch_json_with_retry(
            url,
            headers={"Accept": "application/json"},
        )
    except Exception as e:
        print(f"  WARNING: request failed for {symbol}: {e}", file=sys.stderr)
        return None

    reports = data.get("reports", [])

    mouse_count = 0
    zebrafish_count = 0

    for report in reports:
        gene = report.get("gene", {})
        tax_id = gene.get("tax_id")
        if tax_id is None:
            # Try parsing from taxname
            taxname = gene.get("taxname", "")
            if taxname == "Mus musculus":
                mouse_count += 1
            elif taxname == "Danio rerio":
                zebrafish_count += 1
            continue

        if isinstance(tax_id, str):
            try:
                tax_id = int(tax_id)
            except ValueError:
                continue

        if tax_id == MOUSE_TAXID:
            mouse_count += 1
        elif tax_id == ZEBRAFISH_TAXID:
            zebrafish_count += 1

    return {
        "mouse_count": mouse_count,
        "zebrafish_count": zebrafish_count,
        "has_mouse": mouse_count > 0,
        "has_zebrafish": zebrafish_count > 0,
    }


def load_cache() -> dict:
    """Load cached model organism data if available."""
    if CACHE_FILE.exists():
        with open(CACHE_FILE) as f:
            return json.load(f)
    return {}


def save_cache(cache: dict) -> None:
    """Persist the model organism cache to disk."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f, indent=2, sort_keys=True)
    print(f"  cached: {CACHE_FILE}")


def generate_cue(models_data: dict) -> str:
    """Generate CUE source from model organism data, keyed by HGNC symbol."""
    gene_count = len(models_data)
    lines = [
        "package lacuene",
        "",
        "// Model organisms: mouse (MGI) and zebrafish (ZFIN) ortholog availability.",
        "// Source: NCBI Datasets ortholog API",
        f"// Generated by normalizers/from_models.py -- {gene_count} genes",
        "",
        "genes: {",
    ]

    for symbol in sorted(models_data.keys()):
        entry = models_data[symbol]
        mouse_count = entry.get("mouse_count", 0)
        zebrafish_count = entry.get("zebrafish_count", 0)
        has_mouse = entry.get("has_mouse", False)
        has_zebrafish = entry.get("has_zebrafish", False)

        lines.append(f'\t"{symbol}": {{')
        lines.append(f"\t\t_in_models: true")
        lines.append(f"\t\tmouse_model_count:     {mouse_count}")
        lines.append(f"\t\tzebrafish_model_count: {zebrafish_count}")
        lines.append(f"\t\thas_mouse_model:       {str(has_mouse).lower()}")
        lines.append(f"\t\thas_zebrafish_model:   {str(has_zebrafish).lower()}")
        lines.append(f"\t}}")

    lines.append("}")
    lines.append("")  # trailing newline

    return "\n".join(lines)


def main():
    report = PipelineReport("from_models")
    print("from_models: querying NCBI for model organism orthologs...")

    cache = load_cache()
    models_data = {}
    fetched = 0
    cached_count = 0
    failed = 0

    for symbol in sorted(GENES.keys()):
        ncbi_id = GENES[symbol].get("ncbi", "")
        if not ncbi_id:
            print(f"  {symbol}: no NCBI ID, skipping", file=sys.stderr)
            report.skipped(symbol, "no NCBI ID")
            continue

        if symbol in cache:
            entry = cache[symbol]
            mouse = entry.get("mouse_count", 0)
            zfish = entry.get("zebrafish_count", 0)
            detail = f"mouse={mouse}, zebrafish={zfish}"
            print(f"  {symbol}: cached ({detail})")
            models_data[symbol] = entry
            report.cached(symbol, detail)
            cached_count += 1
            continue

        print(f"  {symbol}: querying NCBI orthologs...", end=" ", flush=True)
        result = fetch_model_organisms(symbol, ncbi_id)
        time.sleep(REQUEST_DELAY)

        if result is None:
            print("FAILED (skipping)", file=sys.stderr)
            report.failed(symbol, "API returned no data")
            failed += 1
            continue

        mouse = result.get("mouse_count", 0)
        zfish = result.get("zebrafish_count", 0)
        detail = f"mouse={mouse}, zebrafish={zfish}"
        print(detail)

        models_data[symbol] = result
        cache[symbol] = result
        report.ok(symbol, detail)
        fetched += 1

    # Save updated cache
    save_cache(cache)

    if not models_data:
        print("ERROR: no model organism data retrieved for any gene", file=sys.stderr)
        sys.exit(1)

    # Write CUE output
    print("from_models: writing model/models.cue...")
    cue_source = generate_cue(models_data)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(cue_source)

    # Stats
    has_mouse = sum(1 for d in models_data.values() if d.get("has_mouse", False))
    has_zebrafish = sum(1 for d in models_data.values() if d.get("has_zebrafish", False))

    print(f"from_models: wrote {OUTPUT_FILE}")
    print(f"  {len(models_data)} genes, {has_mouse} with mouse orthologs, {has_zebrafish} with zebrafish orthologs")
    print(f"  ({fetched} fetched, {cached_count} cached, {failed} failed)")
    print(report.summary())


if __name__ == "__main__":
    main()
